#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "📝 Checking commit message format..."

# Check commit message format with commitlint
npx --no-install commitlint --edit "$1"

echo "✅ Commit message format is valid!"